# Generated by Django 4.1.8 on 2023-05-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheap_Homes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Price', models.BigIntegerField()),
                ('CoverImageUrl', models.CharField(max_length=2000, verbose_name='Cover Image Url')),
            ],
        ),
        migrations.CreateModel(
            name='Dream_Mansions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Price', models.BigIntegerField()),
                ('CoverImageUrl', models.CharField(max_length=2000, verbose_name='Cover Image Url')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(editable=False, max_length=50, verbose_name='First Name')),
                ('LastName', models.CharField(editable=False, max_length=50, verbose_name='First Name')),
                ('Mobile_No', models.CharField(editable=False, max_length=20, verbose_name='Mobile No')),
                ('Email', models.EmailField(editable=False, max_length=254)),
                ('Message', models.TextField(editable=False)),
            ],
        ),
    ]
