# Generated by Django 4.1.8 on 2023-05-30 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cheap_Homes',
            new_name='Cheap_Home',
        ),
        migrations.RenameModel(
            old_name='Dream_Mansions',
            new_name='Dream_Mansion',
        ),
        migrations.RenameModel(
            old_name='Enquiries',
            new_name='Enquirie',
        ),
    ]
