# Generated by Django 4.1.8 on 2023-05-31 23:10

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0002_rename_cheap_homes_cheap_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheap_home',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 0, 10, 38, 176979), editable=False, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='cheap_home',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('3de76905-6745-49c7-84cc-23c11728e686'), editable=False),
        ),
        migrations.AddField(
            model_name='dream_mansion',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 0, 10, 38, 177980), editable=False, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='dream_mansion',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('4ce684eb-2d33-4fd3-bf64-0db5977501ce'), editable=False),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='Price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='Price',
            field=models.CharField(max_length=200),
        ),
    ]
