# Generated by Django 4.1.8 on 2023-06-01 00:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0003_cheap_home_datepub_cheap_home_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirie',
            name='Subject',
            field=models.CharField(default='Property Enquiry', max_length=400),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 1, 2, 7, 710610), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('695dc0d7-cd49-459b-be93-eea903580d35'), editable=False),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 1, 2, 7, 711622), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('698ff7ea-92bb-419b-816e-c2db4a0f1fcb'), editable=False),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='FirstName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='LastName',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='Message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='Mobile_No',
            field=models.CharField(max_length=20, verbose_name='Mobile No'),
        ),
    ]
