# Generated by Django 4.1.8 on 2023-06-01 01:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0005_alter_cheap_home_datepub_alter_cheap_home_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheap_home',
            name='Description',
            field=models.TextField(default='\n\n        This comfortable 2-bedroom bungalow with roof terrace is situated in a quiet location and has a shared swimming pool.\n        \n        The house comprises an open plan fully fitted kitchen/dining/living area, two bedrooms and two bathrooms.\n        \n        The living room has patio doors opening onto a paved terrace covered by a retractable awning.\n        \n        There is stone paving right round the house and gravelled areas for low-maintenance gardening.\n        \n        External steps lead up to the large, tiled roof terrace, from which vantage point stunning views are afforded over serene countryside and olive groves to the majestic White Mountain range.\n        \n        Being only 7km from the white, sandy beaches of Almirida, this makes the perfect holiday home for those wanting peace and quiet, but who also want to be close enough to the larger villages of Almirida or Kalives with their white, sandy beaches and all shopping amenities, post office, banks, supermarkets, tavernas, restaurants & coffee shops.\n        \n        The traditional village of Drapanos has a well-stocked mini-market and a few tavernas with delicious Cretan cuisine.\n        \n        BENEFITS:\n        \n        Air Conditioning\n        Solar Panel\n        Plumbing for Central Heating\n        Aluminium Windows & Doors with Double Glazing & Security Shutters\n        Storage Area\n        Garden\n        Shared Swimming Pool\n        BBQ\n        Roof Terrace\n        Pergola\n        All White Goods Included\n        Fully Furnished\n        Quiet Area\n        Country & Mountain Views\n        Within Walking Distance to Village Square and Local Amenities\n        Short Drive to the Beach & further Amenities\n\n'),
        ),
        migrations.AddField(
            model_name='dream_mansion',
            name='Description',
            field=models.TextField(default='\n\n        This comfortable 2-bedroom bungalow with roof terrace is situated in a quiet location and has a shared swimming pool.\n        \n        The house comprises an open plan fully fitted kitchen/dining/living area, two bedrooms and two bathrooms.\n        \n        The living room has patio doors opening onto a paved terrace covered by a retractable awning.\n        \n        There is stone paving right round the house and gravelled areas for low-maintenance gardening.\n        \n        External steps lead up to the large, tiled roof terrace, from which vantage point stunning views are afforded over serene countryside and olive groves to the majestic White Mountain range.\n        \n        Being only 7km from the white, sandy beaches of Almirida, this makes the perfect holiday home for those wanting peace and quiet, but who also want to be close enough to the larger villages of Almirida or Kalives with their white, sandy beaches and all shopping amenities, post office, banks, supermarkets, tavernas, restaurants & coffee shops.\n        \n        The traditional village of Drapanos has a well-stocked mini-market and a few tavernas with delicious Cretan cuisine.\n        \n        BENEFITS:\n        \n        Air Conditioning\n        Solar Panel\n        Plumbing for Central Heating\n        Aluminium Windows & Doors with Double Glazing & Security Shutters\n        Storage Area\n        Garden\n        Shared Swimming Pool\n        BBQ\n        Roof Terrace\n        Pergola\n        All White Goods Included\n        Fully Furnished\n        Quiet Area\n        Country & Mountain Views\n        Within Walking Distance to Village Square and Local Amenities\n        Short Drive to the Beach & further Amenities\n\n'),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 2, 31, 49, 359665), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('298c2b60-1d63-4ff9-888b-25f0ebc84bd2'), editable=False),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 2, 31, 49, 361665), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('c753e872-14ec-4b66-90bd-90d5c04f461b'), editable=False),
        ),
        migrations.CreateModel(
            name='DreamMansionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(default=datetime.datetime(2023, 6, 1, 2, 31, 49, 362664))),
                ('ImageUrl', models.CharField(max_length=2000)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('DreamMansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.dream_mansion')),
            ],
        ),
        migrations.CreateModel(
            name='CheapHomeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(default=datetime.datetime(2023, 6, 1, 2, 31, 49, 377717))),
                ('ImageUrl', models.CharField(max_length=2000)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('CheapHomes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.cheap_home')),
            ],
        ),
    ]
