# Generated by Django 4.1.8 on 2023-06-06 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0009_alter_cheap_home_datepub_alter_cheap_home_unique_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=200)),
                ('DatePub', models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 18, 50, 819344), verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DollarsPrice', models.CharField(default='$50,000', max_length=50)),
                ('EurosPrice', models.CharField(default='€20,000', max_length=50)),
                ('PoundsPrice', models.CharField(default='£35,000', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cheap_home',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='dream_mansion',
            name='Price',
        ),
        migrations.AddField(
            model_name='cheap_home',
            name='DollarsPrice',
            field=models.CharField(default='$50,000', max_length=50),
        ),
        migrations.AddField(
            model_name='cheap_home',
            name='EurosPrice',
            field=models.CharField(default='€20,000', max_length=50),
        ),
        migrations.AddField(
            model_name='cheap_home',
            name='PoundsPrice',
            field=models.CharField(default='£35,000', max_length=50),
        ),
        migrations.AddField(
            model_name='dream_mansion',
            name='DollarsPrice',
            field=models.CharField(default='$50,000', max_length=50),
        ),
        migrations.AddField(
            model_name='dream_mansion',
            name='EurosPrice',
            field=models.CharField(default='€20,000', max_length=50),
        ),
        migrations.AddField(
            model_name='dream_mansion',
            name='PoundsPrice',
            field=models.CharField(default='£35,000', max_length=50),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 18, 50, 820344), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cheaphomeimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 18, 50, 821344)),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 18, 50, 820344), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dreammansionimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 18, 50, 821344)),
        ),
    ]
