# Generated by Django 4.1.8 on 2023-06-06 01:23

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0010_emails_price_remove_cheap_home_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheap_home',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 23, 48, 596081), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('13904666-d328-4746-939b-a8ff9a850fdd'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cheaphomeimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 23, 48, 598081)),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 23, 48, 597081), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dreammansionimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 23, 48, 597081)),
        ),
        migrations.AlterField(
            model_name='emails',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 23, 48, 595080), verbose_name='Date Created'),
        ),
    ]
