# Generated by Django 4.1.8 on 2023-06-06 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0013_delete_price_alter_cheap_home_datepub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheap_home',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 31, 24, 975085), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='DollarsPrice',
            field=models.CharField(default='$50,000', max_length=50, verbose_name='Dollar Price'),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='EurosPrice',
            field=models.CharField(default='€20,000', max_length=50, verbose_name='Euros Price'),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='PoundsPrice',
            field=models.CharField(default='£35,000', max_length=50, verbose_name='Pounds Price'),
        ),
        migrations.AlterField(
            model_name='cheaphomeimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 31, 24, 976085)),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 31, 24, 975085), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dreammansionimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 31, 24, 976085)),
        ),
        migrations.AlterField(
            model_name='emails',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 2, 31, 24, 974084), verbose_name='Date Created'),
        ),
    ]
