# Generated by Django 4.1.8 on 2023-06-06 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0014_alter_cheap_home_datepub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheap_home',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 4, 17, 34, 311303), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='Description',
            field=models.TextField(default='\nWrite an organized description of the asset to be displayed. eg\n\nThis five bedroom villa for sale in São Brás de Alportel is just one kilometre from the town centre where there are supermarkets, restaurants, cafes, schools and other shops. Currently listed as a five bedroom property due to the extra annexes adjacent to the main house.\n\nThe main house consists of a formal dining area with a traditional fireplace, a fully fitted kitchen, a good size pantry, lounge with another fireplace, a mezzanine style office, three bedrooms, one large family bathroom and a conservatory with a BBQ installed, sink and seating area. \n\nThere is a further large bedroom, currently being used as a storage room, and a bathroom in one of the annexes with the second annex comprising the fifth bedroom, however, both annexes do need refurbishing.\n\nAdditional features include: two entrances to the property, a fountain, solid wood carpentry in the wardrobes, front gate on the road, cobblestone driveway, solar panels for water, double glazed windows and this property is sold furnished but is negotiable. \n\n São Bras is a popular town amongst people that relocate to the Algarve as it has friendly locals and a slower pace of life. In an elevated position north of Faro, the whole area offers lovely views down towards the sea.  - REF: IDH32943\n'),
        ),
        migrations.AlterField(
            model_name='cheaphomeimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 4, 17, 34, 313303)),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 4, 17, 34, 312303), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='Description',
            field=models.TextField(default='\nWrite an organized description of the asset to be displayed. eg\n\nThis five bedroom villa for sale in São Brás de Alportel is just one kilometre from the town centre where there are supermarkets, restaurants, cafes, schools and other shops. Currently listed as a five bedroom property due to the extra annexes adjacent to the main house.\n\nThe main house consists of a formal dining area with a traditional fireplace, a fully fitted kitchen, a good size pantry, lounge with another fireplace, a mezzanine style office, three bedrooms, one large family bathroom and a conservatory with a BBQ installed, sink and seating area. \n\nThere is a further large bedroom, currently being used as a storage room, and a bathroom in one of the annexes with the second annex comprising the fifth bedroom, however, both annexes do need refurbishing.\n\nAdditional features include: two entrances to the property, a fountain, solid wood carpentry in the wardrobes, front gate on the road, cobblestone driveway, solar panels for water, double glazed windows and this property is sold furnished but is negotiable. \n\n São Bras is a popular town amongst people that relocate to the Algarve as it has friendly locals and a slower pace of life. In an elevated position north of Faro, the whole area offers lovely views down towards the sea.  - REF: IDH32943\n'),
        ),
        migrations.AlterField(
            model_name='dreammansionimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 4, 17, 34, 312303)),
        ),
        migrations.AlterField(
            model_name='emails',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 4, 17, 34, 311303), verbose_name='Date Created'),
        ),
    ]
