# Generated by Django 3.2.7 on 2023-06-16 00:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0015_alter_cheap_home_datepub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheap_home',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 1, 8, 52, 508565), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cheaphomeimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 1, 8, 52, 512564)),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 1, 8, 52, 509565), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dreammansionimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 1, 8, 52, 510564)),
        ),
        migrations.AlterField(
            model_name='emails',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 1, 8, 52, 508565), verbose_name='Date Created'),
        ),
        migrations.CreateModel(
            name='DreamMansionPropertie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
                ('Name', models.CharField(default='Plot size', max_length=50)),
                ('Value', models.CharField(default='1200 m2', max_length=50)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('DreamMansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.dream_mansion')),
            ],
        ),
        migrations.CreateModel(
            name='DreamMansionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
                ('Feature', models.CharField(default='Garden', max_length=50)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('DreamMansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.dream_mansion')),
            ],
        ),
        migrations.CreateModel(
            name='CheapHomePropertie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
                ('Name', models.CharField(default='Plot size', max_length=50)),
                ('Value', models.CharField(default='1200 m2', max_length=50)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('DreamMansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.cheap_home')),
            ],
        ),
        migrations.CreateModel(
            name='CheapHomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(default=datetime.datetime.now)),
                ('Feature', models.CharField(default='Garden', max_length=50)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('DreamMansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.cheap_home')),
            ],
        ),
    ]
