# Generated by Django 3.2.7 on 2023-06-16 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0016_auto_20230616_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheaphomefeature',
            old_name='DreamMansion',
            new_name='CheapHomes',
        ),
        migrations.RenameField(
            model_name='cheaphomepropertie',
            old_name='DreamMansion',
            new_name='CheapHomes',
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 7, 13, 6, 254871), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cheaphomeimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 7, 13, 6, 258874)),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 7, 13, 6, 254871), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dreammansionimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 7, 13, 6, 255871)),
        ),
        migrations.AlterField(
            model_name='emails',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 7, 13, 6, 253872), verbose_name='Date Created'),
        ),
    ]
