# Generated by Django 3.2.7 on 2023-07-02 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0017_auto_20230616_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream_mansion',
            name='DisplayTitle',
            field=models.CharField(default='4 Bed Villa', max_length=200),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 20, 41, 41, 883688), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cheaphomeimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 20, 41, 41, 899685)),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 20, 41, 41, 888683), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dreammansionimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 20, 41, 41, 891686)),
        ),
        migrations.AlterField(
            model_name='emails',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 20, 41, 41, 879682), verbose_name='Date Created'),
        ),
    ]
