# Generated by Django 3.2.7 on 2023-07-05 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0018_auto_20230702_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheap_home',
            name='DisplayTitle',
            field=models.CharField(default='4 Bed Villa', max_length=200),
        ),
        migrations.AlterField(
            model_name='cheap_home',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 7, 57, 12, 181333), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='cheaphomeimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 7, 57, 12, 187334)),
        ),
        migrations.AlterField(
            model_name='dream_mansion',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 7, 57, 12, 182333), editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='dreammansionimage',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 7, 57, 12, 184334)),
        ),
        migrations.AlterField(
            model_name='emails',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 7, 57, 12, 181333), verbose_name='Date Created'),
        ),
    ]
